#pragma once

#include <QFrame>
#include <QPointer>
#include <QVector>
#include <QWidget>
#include <vector>

#include <obs-frontend-api.h>

#include "switch-automation-engine.hpp"
#include "switch-canvas-manager.hpp"
#include "switch-motion-manager.hpp"
#include "switcher-dock.hpp"

class QComboBox;
class QGridLayout;
class QLabel;
class QLineEdit;
class QListWidget;
class QListWidgetItem;
class QMenu;
class QAction;
class QPushButton;
class QCheckBox;
class QContextMenuEvent;
class QEvent;
class QHideEvent;
class QMainWindow;
class QDockWidget;
class QDoubleSpinBox;
class QMouseEvent;
class QScrollArea;
class QSlider;
class QShowEvent;
class QSplitter;
class QStackedWidget;
class QToolButton;
class QTreeWidget;
class QResizeEvent;
class QObject;
class QSpinBox;
class QTabWidget;
class SwitchVerticalDockWidget;
class SwitchVerticalScenesDockWidget;
class SwitchVerticalSourcesDockWidget;
class SwitchVerticalTransitionsDockWidget;
class SwitchVerticalSettingsDockWidget;

class SwitcherWorkspacePreview : public QWidget {
	Q_OBJECT

public:
	explicit SwitcherWorkspacePreview(QWidget *parent = nullptr);
	~SwitcherWorkspacePreview() override;

	void SetSource(const OBSSource &source);
	OBSSource GetSource() const;
	void SetPreviewActive(bool active);
	void RefreshActiveState();

signals:
	void ContextMenuRequested(const QPoint &globalPos);

protected:
	void changeEvent(QEvent *event) override;
	void showEvent(QShowEvent *event) override;
	void hideEvent(QHideEvent *event) override;
	bool eventFilter(QObject *watched, QEvent *event) override;

private:
	static void DrawPreview(void *data, uint32_t cx, uint32_t cy);
	bool HandleMouseButtonEvent(QMouseEvent *event);
	bool HandleContextMenuEvent(QContextMenuEvent *event);
	bool ShouldActivatePreview() const;
	void ActivatePreview();
	void DeactivatePreview();
	void DestroyPreviewDisplay();
	void UpdatePreviewLifecycle();

	OBSQTDisplay *display = nullptr;
	OBSSource source = nullptr;
	bool previewConfigured = false;
	bool previewActive = false;
	bool drawCallbackInstalled = false;
};

class SwitcherWorkspaceSlot : public QFrame {
	Q_OBJECT

public:
	explicit SwitcherWorkspaceSlot(int slotIndex, QWidget *parent = nullptr);

	void SetSource(const OBSSource &source);
	OBSSource GetSource();

	void SetCustomTitle(const QString &title);
	QString GetCustomTitle() const;
	QString GetEffectiveTitle() const;

	void SetPreviewActive(bool active);
	void SetSelected(bool active);
	void RefreshActiveState();
	void ClearIfMatches(obs_source_t *source);
	void ShowContextMenu(const QPoint &globalPos);

signals:
	void ConfigureRequested(int slotIndex);
	void AdvancedRequested(int slotIndex);
	void DetachRequested(int slotIndex);
	void VerticalDetachRequested(int slotIndex);

protected:
	void contextMenuEvent(QContextMenuEvent *event) override;
	void mouseReleaseEvent(QMouseEvent *event) override;
	void resizeEvent(QResizeEvent *event) override;

private:
	void RefreshPresentation();
	void RefreshTitleLabel();
	void RefreshSelectionState();
	QString DefaultTitle() const;

	int slotIndex;
	QString customTitle;
	SwitcherWorkspacePreview *previewWidget;
	QStackedWidget *contentStack;
	QLabel *emptyLabel;
	QLabel *titleLabel;
	QMenu *contextMenu;
	QAction *editAction;
	QAction *advancedAction;
	QAction *detachAction;
	QAction *verticalDetachAction;
	bool previewActive = false;
	bool selected = false;
};

class SwitcherWorkspaceDock : public QWidget {
	Q_OBJECT

public:
	explicit SwitcherWorkspaceDock(QMainWindow *parent = nullptr);
	~SwitcherWorkspaceDock() override;

	void OpenWorkspaceWindow();
	obs_data_t *SaveState();
	void LoadState(obs_data_t *data);
	void ApplySerializedContentState(const char *json);
	void HandleSourceRemoved(obs_source_t *source);
	void HandleFrontendEvent(enum obs_frontend_event event);
	void ClearSceneCollectionState(bool duringFrontendShutdown = false, bool preserveMotionState = false);
	int VisibleSlotCount() const;
	OBSSource SlotSource(int index) const;
	QString SlotTitle(int index) const;
	obs_data_t *BuildCanvasState() const;
	obs_data_t *BuildAutomationState() const;
	obs_data_t *BuildMotionState() const;
	SwitchCanvasManager *CanvasManager() const;
	SwitchCanvasDescriptor CanvasDescriptorForId(const QString &canvasId) const;
	QVector<SwitchCanvasSceneDescriptor> CanvasScenes(const QString &canvasId) const;
	QVector<SwitchCanvasSourceDescriptor> CanvasSources(const QString &canvasId) const;
	QString VerticalCanvasId() const;
	bool SwitchCanvasScene(const QString &canvasId, const QString &sceneIdOrName);
	bool CreateCanvasScene(const QString &canvasId, const QString &baseName, QString *createdName = nullptr);
	bool DuplicateCanvasScene(const QString &canvasId, const QString &sceneIdOrName, const QString &baseName,
				 QString *createdName = nullptr);
	bool DeleteCanvasScene(const QString &canvasId, const QString &sceneIdOrName);
	bool RenameCanvasScene(const QString &canvasId, const QString &sceneIdOrName, const QString &name);
	bool SetCanvasSourceVisible(const QString &canvasId, int itemId, bool visible);
	bool SetCanvasSourceLocked(const QString &canvasId, int itemId, bool locked);
	bool RenameCanvasSource(const QString &canvasId, int itemId, const QString &name);
	bool DeleteCanvasSource(const QString &canvasId, int itemId);
	bool MoveCanvasSource(const QString &canvasId, int itemId, obs_order_movement movement);
	bool OpenCanvasSourceProperties(const QString &canvasId, int itemId);
	bool OpenCanvasSourceFilters(const QString &canvasId, int itemId);
	bool SetCanvasLink(const QString &mainSceneUuid, const QString &targetSceneIdOrName);
	bool OpenCanvasWindow(const QString &canvasId);
	bool OpenCanvasProjector(const QString &canvasId);
	bool PerformOutputAction(const QString &action, const QString &value = QString());
	QString CreateAutomationMacro(const QString &name);
	bool DeleteAutomationMacro(const QString &macroId);
	bool UpdateAutomationMacro(const SwitchMacroDescriptor &macro);
	bool UpsertAutomationMacro(const SwitchAutomationMacro &macro, QString *effectiveId = nullptr);
	SwitchAutomationMacro AutomationMacroDefinition(const QString &macroId) const;
	bool SetAutomationMacroEnabled(const QString &macroId, bool enabled);
	bool SetAutomationMacroPaused(const QString &macroId, bool paused);
	bool TriggerAutomationMacro(const QString &macroId, QString *message = nullptr);
	bool SetAutomationVariable(const QString &key, const QString &value);
	bool DeleteAutomationVariable(const QString &key);
	bool ClearAutomationQueue(const QString &queueId);
	SwitchAutomationConnection AutomationConnection(const QString &connectionId) const;
	bool TestAutomationConnection(const QString &connectionId, QString *message = nullptr);
	SwitchMotionProfile MotionProfileDefinition(const QString &profileId) const;
	bool UpsertMotionProfile(const SwitchMotionProfile &profile, QString *effectiveId = nullptr);
	bool DeleteMotionProfile(const QString &profileId);
	bool SetMotionEnabled(const QString &profileId, bool enabled);
	bool BindMotionSource(const QString &sourceUuid, const QString &sourceName, const QString &profileId,
			      QString *message = nullptr);
	bool UnbindMotionSource(const QString &sourceUuid, QString *message = nullptr);
	SwitchMotionShot MotionShotDefinition(const QString &shotId) const;
	bool UpsertMotionShot(const SwitchMotionShot &shot, QString *effectiveId = nullptr);
	bool DeleteMotionShot(const QString &shotId);
	bool SetMotionShotEnabled(const QString &shotId, bool enabled);
	bool BindMotionSceneItem(const SwitchMotionShot &shot, QString *effectiveId = nullptr,
				 QString *message = nullptr);

protected:
	void showEvent(QShowEvent *event) override;
	void hideEvent(QHideEvent *event) override;
	void resizeEvent(QResizeEvent *event) override;
	void changeEvent(QEvent *event) override;

private slots:
	void LayoutChanged();
	void SelectedSlotChanged();
	void SelectedSceneChanged();
	void SelectedTitleChanged(const QString &title);
	void ClearSelectedSlot();
	void OpenSelectedSlotAsDock();
	void OpenSelectedSlotAsVerticalDock();
	void OpenSelectedSlotProjector();
	void ToggleSelectedSlotRecording();
	void ToggleSelectedSlotRecordingPause();
	void SplitSelectedSlotRecording();
	void ToggleSelectedSlotReplayBuffer();
	void SaveSelectedSlotReplayBuffer();
	void ToggleSelectedSlotStreaming();
	void ToggleSelectedSlotVirtualCam();
	void OpenSlotAsDock(int slotIndex);
	void OpenSlotAsVerticalDock(int slotIndex);
	void OpenSelectedSlotInspector();
	void RemoteStateUpdated();
	void RemoteEnabledChanged(Qt::CheckState state);
	void RemoteAutoStartChanged(Qt::CheckState state);
	void RemoteResolutionChanged(int index);
	void RemoteFpsChanged(int index);
	void CopyRemoteUrl();
	void RegenerateRemoteToken();
	void RestartRemote();
	void ModeChanged(int index);
	void VerticalCanvasNameChanged(const QString &name);
	void VerticalPresetChanged(int index);
	void VerticalSceneSelectionChanged();
	void AddVerticalScene();
	void RemoveSelectedVerticalScene();
	void OpenVerticalCanvasWindow();
	void OpenVerticalCanvasProjector();
	void OpenVerticalCanvasDock();
	void OpenVerticalScenesDock();
	void OpenVerticalSourcesDock();
	void OpenVerticalTransitionsDock();
	void OpenVerticalSettingsDock();
	void LinkCurrentProgramSceneToSelectedVerticalScene();
	void ClearSelectedVerticalLink();
	void VerticalLinkedSyncChanged(Qt::CheckState state);
	void VerticalTransitionChanged(int index);
	void VerticalTransitionDurationChanged(int value);
	void OpenVerticalOutputSettings();
	void MotionSelectionChanged();
	void MotionNameChanged(const QString &name);
	void MotionEnabledChanged(Qt::CheckState state);
	void MotionConfidenceChanged(double value);
	void MotionMaxZoomChanged(double value);
	void MotionFramingMarginChanged(double value);
	void MotionDeadZoneChanged(double value);
	void MotionSmoothingChanged(double value);
	void MotionHoldChanged(int value);
	void AddMotionProfile();
	void DeleteSelectedMotionProfile();
	void BindSelectedMotionSource();
	void UnbindSelectedMotionSource();
	void MotionShotSelectionChanged();
	void MotionShotSceneChanged(int index);
	void MotionShotItemChanged(int index);
	void AddMotionShot();
	void DeleteSelectedMotionShot();
	void DuplicateSelectedMotionShot();
	void BindSelectedMotionShot();
	void AddRecordingChapter();
	void MacroSelectionChanged();
	void AddMacro();
	void DeleteSelectedMacro();
	void RunSelectedMacro();
	void DuplicateSelectedMacro();
	void ExportSelectedMacro();
	void ImportMacro();
	void MacroNameChanged(const QString &name);
	void MacroEnabledChanged(Qt::CheckState state);
	void MacroPausedChanged(Qt::CheckState state);
	void MacroRunModeChanged(int index);
	void MacroTriggerTypeChanged(int index);
	void MacroIntervalChanged(int value);
	void MacroTriggerConnectionChanged(int index);
	void MacroTriggerSceneChanged(int index);
	void MacroTriggerStateChanged(int index);
	void MacroTriggerKeyChanged(const QString &value);
	void MacroTriggerValueChanged(const QString &value);
	void MacroActionTypeChanged(int index);
	void MacroActionConnectionChanged(int index);
	void MacroActionSceneChanged(int index);
	void MacroActionDelayChanged(int value);
	void MacroActionKeyChanged(const QString &value);
	void MacroActionValueChanged(const QString &value);
	void SetAutomationVariableFromEditor();
	void RemoveSelectedVariable();
	void ClearSelectedQueue();
	void AddOscConnection();
	void RemoveSelectedConnection();
	void ConnectionSelectionChanged();
	void ConnectionNameChanged(const QString &value);
	void ConnectionModeChanged(int index);
	void ConnectionRemoteHostChanged(const QString &value);
	void ConnectionRemotePortChanged(int value);
	void ConnectionListenHostChanged(const QString &value);
	void ConnectionListenPortChanged(int value);
	void TestSelectedConnection();
	void ExportAutomationDocument();
	void ImportAutomationDocument();

private:
	enum class SettingsPanelMode { Workspace, SlotInspector };

	static bool AddSceneOption(void *data, obs_source_t *source);

	obs_data_t *SaveContentState() const;
	void LoadContentState(obs_data_t *data, bool emitSignal);
	void RegisterUndoRedoAction(const char *name, obs_data_t *before, obs_data_t *after, bool repeatable = false);
	void ApplyPreviewState(bool enabled);
	void ApplyTheme();
	SwitcherWorkspaceSlot *CurrentSlot() const;
	QString CurrentSlotLabel() const;
	int SelectedSlotIndex() const;
	void RefreshGrid();
	void RefreshSceneOptions();
	void RefreshSettingsPanelMode();
	void RefreshSelectedSlotEditor();
	void RefreshOutputActions();
	void RefreshSlotList();
	void RefreshRemoteControls();
	void RefreshSelectionHighlights();
	void UpdateInspectorVisibility(bool visible);
	void ApplyDefaultWindowGeometry();
	void OpenSlotSettings(int slotIndex);
	void OpenAdvancedSettings(int slotIndex);
	void ShowSettingsPanel(SettingsPanelMode mode);
	void HideSettingsPanel();
	void ScheduleVerticalRefresh();
	void RefreshVerticalPage();
	void RefreshVerticalObsDock();
	void RefreshVerticalDockSurfaces();
	void RefreshVerticalSettingsSummary();
	void RefreshMotionPage();
	void ScheduleMotionRuntimeRefresh();
	void RefreshMotionProfiles();
	void RefreshMotionEditor();
	void RefreshMotionSources();
	void RefreshMotionBindings();
	void RefreshMotionShots();
	void RefreshMotionShotEditor();
	void RefreshMotionShotSceneItems();
	void RefreshMotionRuntimeStatus();
	bool FrontendApisAvailable() const;
	void UnregisterVerticalObsDocks();
	void AppendVerticalSceneItem(const QString &sceneName, bool selectItem = false);
	void ApplyVerticalSceneSelectionUi(const QString &sceneName);
	void ShowVerticalSceneContextMenu(const QPoint &pos);
	void ShowVerticalSourceContextMenu(const QPoint &pos);
	QString SelectedVerticalSceneId() const;
	QString SelectedVerticalSceneName() const;
	int SelectedVerticalSourceItemId() const;
	bool RenameVerticalSource(int itemId, const QString &name);
	bool RemoveVerticalSource(int itemId);
	bool MoveVerticalSource(int itemId, obs_order_movement movement);
	void OpenVerticalSourceProperties(int itemId);
	void OpenVerticalSourceFilters(int itemId);
	void ApplySelectedSceneTransitionOverride();
	void ClearSelectedSceneTransitionOverride();
	void RefreshAutomationPage();
	void RefreshMacroList();
	void RefreshMacroEditor();
	void RefreshAutomationVariables();
	void RefreshAutomationQueues();
	void RefreshAutomationConnections();
	void RefreshAutomationConnectionEditor();
	void RefreshAutomationEventLog();
	void RefreshAutomationStatus();
	void UpdateSelectedMacroFromEditor();
	void UpdateSelectedConnectionFromEditor();
	QString SelectedMacroId() const;
	QString SelectedQueueId() const;
	QString SelectedConnectionId() const;
	void EmitCanvasVendorStateChanged() const;
	void EmitAutomationVendorStateChanged(const QString &macroId = QString(), bool success = true,
					      const QString &message = QString()) const;
	void EmitMotionVendorStateChanged(const QString &profileId = QString()) const;
	bool EnsureVerticalObsDock(bool visible);
	bool EnsureVerticalScenesObsDock(bool visible);
	bool EnsureVerticalSourcesObsDock(bool visible);
	bool EnsureVerticalTransitionsObsDock(bool visible);
	bool EnsureVerticalSettingsObsDock(bool visible);
	void InstallQuickOutputControls();
	void RemoveQuickOutputControls();
	void UpdateQuickOutputControls();
	void SelectMode(int index, bool force = false);
	void UpdateModeButtons();
	void UpdateVerticalPreviewAspect();
	void PlaceVerticalObsDock();
	void ToggleQuickOutputProjector(bool multiview);
	void OpenQuickOutputProjector(bool multiview);
	void CloseQuickOutputProjector(bool multiview);
	void TrackQuickOutputProjector(bool multiview, QWidget *window);
	bool QuickOutputProjectorActive(bool multiview) const;
	void ShowQuickOutputMonitorMenu(bool multiview);

	QFrame *modeList;
	QVector<QPushButton *> modeButtons;
	int currentModeIndex = 0;
	QStackedWidget *modeStack;
	QWidget *workspaceModePage;
	QWidget *verticalModePage;
	QWidget *motionModePage;
	QWidget *automationModePage;
	QWidget *remoteModePage;
	QSplitter *contentSplitter;
	QScrollArea *scrollArea;
	QWidget *gridContainer;
	QGridLayout *gridLayout;
	QFrame *inspectorFrame;
	QToolButton *inspectorModeButton;
	QLabel *inspectorTitleLabel;
	QToolButton *inspectorCloseButton;
	QStackedWidget *inspectorStack;
	QWidget *workspacePage;
	QWidget *slotPage;
	QWidget *workspaceSettingsSection;
	QWidget *slotEditorSection;
	QWidget *slotOutputSection;
	QWidget *remoteSettingsSection;
	QListWidget *slotList;
	QComboBox *layoutCombo;
	QComboBox *sceneCombo;
	QLineEdit *titleEdit;
	QPushButton *clearSlotButton;
	QPushButton *detachSlotButton;
	QPushButton *verticalDetachSlotButton;
	QLabel *slotOutputStatusLabel;
	QPushButton *slotProjectorButton;
	QPushButton *slotRecordButton;
	QPushButton *slotPauseRecordButton;
	QPushButton *slotSplitRecordButton;
	QPushButton *slotReplayButton;
	QPushButton *slotReplaySaveButton;
	QPushButton *slotStreamButton;
	QPushButton *slotVirtualCamButton;
	QCheckBox *remoteEnabledCheckBox;
	QCheckBox *remoteAutoStartCheckBox;
	QComboBox *remoteResolutionCombo;
	QComboBox *remoteFpsCombo;
	QLineEdit *remoteUrlEdit;
	QLabel *remoteStatusLabel;
	QPushButton *remoteCopyButton;
	QPushButton *remoteRegenerateButton;
	QPushButton *remoteRestartButton;
	SwitchCanvasManager *canvasManager;
	SwitchAutomationEngine *automationEngine;
	SwitchMotionManager *motionManager;
	QLineEdit *verticalCanvasNameEdit;
	QComboBox *verticalPresetCombo;
	QWidget *verticalCanvasPreviewFrame = nullptr;
	QCheckBox *verticalLinkedSyncCheckBox;
	QComboBox *verticalTransitionCombo;
	QSpinBox *verticalTransitionDurationSpin;
	QTabWidget *verticalSurfaceTabs;
	QLabel *verticalCanvasStatusLabel;
	QListWidget *verticalSceneList;
	QTreeWidget *verticalSourceTree;
	QPushButton *verticalSceneAddButton;
	QPushButton *verticalSceneRemoveButton;
	QPushButton *verticalSceneMenuButton;
	QPushButton *verticalSourcePropertiesButton;
	QPushButton *verticalSourceFiltersButton;
	QPushButton *verticalSourceMenuButton;
	QPushButton *verticalSceneOpenWindowButton;
	QPushButton *verticalSceneOpenProjectorButton;
	QPushButton *verticalSceneDockButton;
	QPushButton *verticalScenesDockButton;
	QPushButton *verticalSourcesDockButton;
	QPushButton *verticalTransitionsDockButton;
	QPushButton *verticalSettingsDockButton;
	QPushButton *verticalLinkCurrentSceneButton;
	QPushButton *verticalClearLinkButton;
	QListWidget *verticalSceneLinksList;
	QComboBox *verticalSceneOverrideCombo;
	QSpinBox *verticalSceneOverrideDurationSpin;
	QPushButton *verticalApplySceneTransitionButton;
	QPushButton *verticalClearSceneTransitionButton;
	QLabel *verticalOutputSettingsSummaryLabel;
	QPushButton *verticalConfigureOutputsButton;
	QLabel *verticalOutputStatusLabel;
	QPushButton *verticalRecordButton;
	QPushButton *verticalPauseRecordButton;
	QPushButton *verticalSplitRecordButton;
	QPushButton *verticalChapterButton;
	QPushButton *verticalReplayButton;
	QPushButton *verticalReplaySaveButton;
	QPushButton *verticalStreamButton;
	QPushButton *verticalVirtualCamButton;
	SwitchCanvasPreview *verticalCanvasPreview;
	SwitchVerticalDockWidget *verticalObsDockWidget = nullptr;
	QPointer<QDockWidget> verticalObsDockContainer = nullptr;
	bool restoreVerticalObsDockOnHide = false;
	SwitchVerticalScenesDockWidget *verticalScenesObsDockWidget = nullptr;
	QPointer<QDockWidget> verticalScenesObsDockContainer = nullptr;
	SwitchVerticalSourcesDockWidget *verticalSourcesObsDockWidget = nullptr;
	QPointer<QDockWidget> verticalSourcesObsDockContainer = nullptr;
	SwitchVerticalTransitionsDockWidget *verticalTransitionsObsDockWidget = nullptr;
	QPointer<QDockWidget> verticalTransitionsObsDockContainer = nullptr;
	SwitchVerticalSettingsDockWidget *verticalSettingsObsDockWidget = nullptr;
	QPointer<QDockWidget> verticalSettingsObsDockContainer = nullptr;
	QPointer<QWidget> quickOutputContainer;
	QPushButton *quickMultiviewButton = nullptr;
	QPushButton *quickMultiviewConfigButton = nullptr;
	QPushButton *quickProgramButton = nullptr;
	QPushButton *quickProgramConfigButton = nullptr;
	QPointer<QPushButton> quickSwitchButton;
	int quickMultiviewMonitor = -2;
	int quickProgramMonitor = -2;
	QPointer<QWidget> quickMultiviewProjector;
	QPointer<QWidget> quickProgramProjector;
	QListWidget *motionProfileList;
	QPushButton *motionAddButton;
	QPushButton *motionDeleteButton;
	QListWidget *motionShotList;
	QPushButton *motionShotAddButton;
	QPushButton *motionShotDeleteButton;
	QPushButton *motionShotDuplicateButton;
	QPushButton *motionShotBindButton;
	QLabel *motionWorkstationStatusLabel;
	QLabel *motionShotModeHintLabel;
	QLineEdit *motionShotNameEdit;
	QCheckBox *motionShotEnabledCheckBox;
	QComboBox *motionShotSceneCombo;
	QComboBox *motionShotItemCombo;
	QComboBox *motionShotModeCombo;
	QComboBox *motionShotPlaybackCombo;
	QComboBox *motionShotPresetCombo;
	QSpinBox *motionShotDurationSpin;
	QSlider *motionShotDurationSlider;
	QComboBox *motionShotEasingCombo;
	QComboBox *motionShotLoopModeCombo;
	QDoubleSpinBox *motionShotStartPanXSpin;
	QSlider *motionShotStartPanXSlider;
	QDoubleSpinBox *motionShotStartPanYSpin;
	QSlider *motionShotStartPanYSlider;
	QDoubleSpinBox *motionShotStartZoomSpin;
	QSlider *motionShotStartZoomSlider;
	QDoubleSpinBox *motionShotEndPanXSpin;
	QSlider *motionShotEndPanXSlider;
	QDoubleSpinBox *motionShotEndPanYSpin;
	QSlider *motionShotEndPanYSlider;
	QDoubleSpinBox *motionShotEndZoomSpin;
	QSlider *motionShotEndZoomSlider;
	QDoubleSpinBox *motionShotMaxZoomSpin;
	QSlider *motionShotMaxZoomSlider;
	QLineEdit *motionNameEdit;
	QCheckBox *motionEnabledCheckBox;
	QDoubleSpinBox *motionConfidenceSpin;
	QSlider *motionConfidenceSlider;
	QDoubleSpinBox *motionMaxZoomSpin;
	QSlider *motionMaxZoomSlider;
	QDoubleSpinBox *motionFramingMarginSpin;
	QSlider *motionFramingMarginSlider;
	QDoubleSpinBox *motionDeadZoneSpin;
	QSlider *motionDeadZoneSlider;
	QDoubleSpinBox *motionSmoothingSpin;
	QSlider *motionSmoothingSlider;
	QSpinBox *motionHoldSpin;
	QSlider *motionHoldSlider;
	QComboBox *motionBackendCombo;
	QComboBox *motionSubjectModeCombo;
	QComboBox *motionFramingModeCombo;
	QComboBox *motionPresetCombo;
	QDoubleSpinBox *motionTrackerHighSpin;
	QSlider *motionTrackerHighSlider;
	QDoubleSpinBox *motionTrackerLowSpin;
	QSlider *motionTrackerLowSlider;
	QDoubleSpinBox *motionNewTrackSpin;
	QSlider *motionNewTrackSlider;
	QSpinBox *motionTrackBufferSpin;
	QSpinBox *motionAutoSwitchSpin;
	QSlider *motionAutoSwitchSlider;
	QDoubleSpinBox *motionPanResponsivenessSpin;
	QSlider *motionPanResponsivenessSlider;
	QDoubleSpinBox *motionTiltResponsivenessSpin;
	QSlider *motionTiltResponsivenessSlider;
	QDoubleSpinBox *motionZoomResponsivenessSpin;
	QSlider *motionZoomResponsivenessSlider;
	QDoubleSpinBox *motionMaxPanSpeedSpin;
	QSlider *motionMaxPanSpeedSlider;
	QDoubleSpinBox *motionMaxTiltSpeedSpin;
	QSlider *motionMaxTiltSpeedSlider;
	QDoubleSpinBox *motionMaxZoomSpeedSpin;
	QSlider *motionMaxZoomSpeedSlider;
	QCheckBox *motionDebugOverlayCheckBox;
	QLineEdit *motionModelPathEdit;
	QComboBox *motionSourceCombo;
	QPushButton *motionBindButton;
	QPushButton *motionUnbindButton;
	QListWidget *motionBindingList;
	QLabel *motionRuntimeStatusLabel;
	QLabel *motionTargetStatusLabel;
	QListWidget *motionTrackList;
	SwitcherWorkspacePreview *motionScenePreview;
	QFrame *motionPositionSection;
	QFrame *motionProfileSection;
	QFrame *motionFramingSection;
	QFrame *motionTrackingSection;
	QFrame *motionControllerSection;
	QPushButton *motionLockCurrentButton;
	QPushButton *motionCyclePreviousButton;
	QPushButton *motionCycleNextButton;
	QPushButton *motionClearLockButton;
	QListWidget *macroList;
	QPushButton *macroAddButton;
	QPushButton *macroDeleteButton;
	QPushButton *macroRunButton;
	QPushButton *macroDuplicateButton;
	QPushButton *macroExportButton;
	QPushButton *macroImportButton;
	QLineEdit *macroNameEdit;
	QCheckBox *macroEnabledCheckBox;
	QCheckBox *macroPausedCheckBox;
	QComboBox *macroRunModeCombo;
	QComboBox *macroTriggerTypeCombo;
	QSpinBox *macroIntervalSpin;
	QComboBox *macroTriggerConnectionCombo;
	QComboBox *macroTriggerSceneCombo;
	QComboBox *macroTriggerStateCombo;
	QLineEdit *macroTriggerKeyEdit;
	QLineEdit *macroTriggerValueEdit;
	QComboBox *macroActionTypeCombo;
	QComboBox *macroActionConnectionCombo;
	QComboBox *macroActionSceneCombo;
	QSpinBox *macroActionDelaySpin;
	QLineEdit *macroActionKeyEdit;
	QLineEdit *macroActionValueEdit;
	QLabel *macroLastResultLabel;
	QTabWidget *automationSurfaceTabs;
	QListWidget *variableList;
	QLineEdit *variableKeyEdit;
	QLineEdit *variableValueEdit;
	QPushButton *variableSetButton;
	QPushButton *variableRemoveButton;
	QListWidget *queueList;
	QPushButton *queueClearButton;
	QListWidget *connectionList;
	QPushButton *connectionAddButton;
	QPushButton *connectionRemoveButton;
	QLineEdit *connectionNameEdit;
	QComboBox *connectionModeCombo;
	QLineEdit *connectionRemoteHostEdit;
	QSpinBox *connectionRemotePortSpin;
	QLineEdit *connectionListenHostEdit;
	QSpinBox *connectionListenPortSpin;
	QLabel *connectionDetailsLabel;
	QPushButton *connectionTestButton;
	QListWidget *eventLogList;
	QLabel *automationStatusSummaryLabel;
	QPushButton *automationExportButton;
	QPushButton *automationImportButton;
	std::vector<SwitcherWorkspaceSlot *> slotWidgets;
	bool previewsEnabled = false;
	bool loadingState = false;
	bool applyingUndoRedo = false;
	bool applyingTheme = false;
	bool loadingVerticalUi = false;
	bool verticalRefreshPending = false;
	bool suppressNextVerticalRefresh = false;
	bool loadingAutomationUi = false;
	bool loadingMotionUi = false;
	bool frontendFinishedLoading = false;
	bool frontendShuttingDown = false;
	bool frontendExiting = false;
	bool workspacePlacementInitialized = false;
	int inspectorWidth = 420;
	SettingsPanelMode settingsPanelMode = SettingsPanelMode::Workspace;
	QString appliedThemeStyleSheet;

signals:
	void WorkspaceStateChanged();
};
